apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hs-mern-himani
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-hs-mern-himani
  template:
    metadata:
      labels:
        app: backend-hs-mern-himani
    spec:
      containers:
      - name: hello-microservice
        image: public.ecr.aws/c3w1m1q2/himani_orches_backend_hello:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice-be-service
spec:
  selector:
    app: backend-hs-mern-himani
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer