apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hs-mern-himani
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-hs-mern-himani
  template:
    metadata:
      labels:
        app: backend-hs-mern-himani
    spec:
      containers:
      - name: profile-microservice
        image: public.ecr.aws/c3w1m1q2/himani_orches_backend_profiles:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: profileservice-be-service
spec:
  selector:
    app: backend-hs-mern-himani
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer